#pragma once
//STM32 IO defines

//GPIOA defines
#define A0_GPIO				GPIOA
#define A0_PIN				0
#define A1_GPIO				GPIOA
#define A1_PIN				1
#define A2_GPIO				GPIOA
#define A2_PIN				2
#define A3_GPIO				GPIOA
#define A3_PIN				3
#define A4_GPIO				GPIOA
#define A4_PIN				4
#define A5_GPIO				GPIOA
#define A5_PIN				5
#define A6_GPIO				GPIOA
#define A6_PIN				6
#define A7_GPIO				GPIOA
#define A7_PIN				7
#define A8_GPIO				GPIOA
#define A8_PIN				8
#define A9_GPIO				GPIOA
#define A9_PIN				9
#define A10_GPIO			GPIOA
#define A10_PIN				10
#define A11_GPIO			GPIOA
#define A11_PIN				11
#define A12_GPIO			GPIOA
#define A12_PIN				12
#define A13_GPIO			GPIOA
#define A13_PIN				13
#define A14_GPIO			GPIOA
#define A14_PIN				14
#define A15_GPIO			GPIOA
#define A15_PIN				15

//GPIOB defines
#define B0_GPIO				GPIOB
#define B0_PIN				0
#define B1_GPIO				GPIOB
#define B1_PIN				1
#define B2_GPIO				GPIOB
#define B2_PIN				2
#define B3_GPIO				GPIOB
#define B3_PIN				3
#define B4_GPIO				GPIOB
#define B4_PIN				4
#define B5_GPIO				GPIOB
#define B5_PIN				5
#define B6_GPIO				GPIOB
#define B6_PIN				6
#define B7_GPIO				GPIOB
#define B7_PIN				7
#define B8_GPIO				GPIOB
#define B8_PIN				8
#define B9_GPIO				GPIOB
#define B9_PIN				9
#define B10_GPIO			GPIOB
#define B10_PIN				10
#define B11_GPIO			GPIOB
#define B11_PIN				11
#define B12_GPIO			GPIOB
#define B12_PIN				12
#define B13_GPIO			GPIOB
#define B13_PIN				13
#define B14_GPIO			GPIOB
#define B14_PIN				14
#define B15_GPIO			GPIOB
#define B15_PIN				15

//GPIOC defines
#define C0_GPIO				GPIOC
#define C0_PIN				0
#define C1_GPIO				GPIOC
#define C1_PIN				1
#define C2_GPIO				GPIOC
#define C2_PIN				2
#define C3_GPIO				GPIOC
#define C3_PIN				3
#define C4_GPIO				GPIOC
#define C4_PIN				4
#define C5_GPIO				GPIOC
#define C5_PIN				5
#define C6_GPIO				GPIOC
#define C6_PIN				6
#define C7_GPIO				GPIOC
#define C7_PIN				7
#define C8_GPIO				GPIOC
#define C8_PIN				8
#define C9_GPIO				GPIOC
#define C9_PIN				9
#define C10_GPIO			GPIOC
#define C10_PIN				10
#define C11_GPIO			GPIOC
#define C11_PIN				11
#define C12_GPIO			GPIOC
#define C12_PIN				12
#define C13_GPIO			GPIOC
#define C13_PIN				13
#define C14_GPIO			GPIOC
#define C14_PIN				14
#define C15_GPIO			GPIOC
#define C15_PIN				15

//GPIOD defines
#define D0_GPIO				GPIOD
#define D0_PIN				0
#define D1_GPIO				GPIOD
#define D1_PIN				1
#define D2_GPIO				GPIOD
#define D2_PIN				2
#define D3_GPIO				GPIOD
#define D3_PIN				3
#define D4_GPIO				GPIOD
#define D4_PIN				4
#define D5_GPIO				GPIOD
#define D5_PIN				5
#define D6_GPIO				GPIOD
#define D6_PIN				6
#define D7_GPIO				GPIOD
#define D7_PIN				7
#define D8_GPIO				GPIOD
#define D8_PIN				8
#define D9_GPIO				GPIOD
#define D9_PIN				9
#define D10_GPIO			GPIOD
#define D10_PIN				10
#define D11_GPIO			GPIOD
#define D11_PIN				11
#define D12_GPIO			GPIOD
#define D12_PIN				12
#define D13_GPIO			GPIOD
#define D13_PIN				13
#define D14_GPIO			GPIOD
#define D14_PIN				14
#define D15_GPIO			GPIOD
#define D15_PIN				15

//GPIOE defines
#define E0_GPIO				GPIOE
#define E0_PIN				0
#define E1_GPIO				GPIOE
#define E1_PIN				1
#define E2_GPIO				GPIOE
#define E2_PIN				2
#define E3_GPIO				GPIOE
#define E3_PIN				3
#define E4_GPIO				GPIOE
#define E4_PIN				4
#define E5_GPIO				GPIOE
#define E5_PIN				5
#define E6_GPIO				GPIOE
#define E6_PIN				6
#define E7_GPIO				GPIOE
#define E7_PIN				7
#define E8_GPIO				GPIOE
#define E8_PIN				8
#define E9_GPIO				GPIOE
#define E9_PIN				9
#define E10_GPIO			GPIOE
#define E10_PIN				10
#define E11_GPIO			GPIOE
#define E11_PIN				11
#define E12_GPIO			GPIOE
#define E12_PIN				12
#define E13_GPIO			GPIOE
#define E13_PIN				13
#define E14_GPIO			GPIOE
#define E14_PIN				14
#define E15_GPIO			GPIOE
#define E15_PIN				15

//GPIOF defines
#define F0_GPIO				GPIOF
#define F0_PIN				0
#define F1_GPIO				GPIOF
#define F1_PIN				1
#define F2_GPIO				GPIOF
#define F2_PIN				2
#define F3_GPIO				GPIOF
#define F3_PIN				3
#define F4_GPIO				GPIOF
#define F4_PIN				4
#define F5_GPIO				GPIOF
#define F5_PIN				5
#define F6_GPIO				GPIOF
#define F6_PIN				6
#define F7_GPIO				GPIOF
#define F7_PIN				7
#define F8_GPIO				GPIOF
#define F8_PIN				8
#define F9_GPIO				GPIOF
#define F9_PIN				9
#define F10_GPIO			GPIOF
#define F10_PIN				10
#define F11_GPIO			GPIOF
#define F11_PIN				11
#define F12_GPIO			GPIOF
#define F12_PIN				12
#define F13_GPIO			GPIOF
#define F13_PIN				13
#define F14_GPIO			GPIOF
#define F14_PIN				14
#define F15_GPIO			GPIOF
#define F15_PIN				15
